
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int TIMES = 27;
  public static final int EXIT = 9;
  public static final int AND = 2;
  public static final int READ = 16;
  public static final int NE = 23;
  public static final int LT = 19;
  public static final int IDENT = 33;
  public static final int ELSE = 12;
  public static final int PLUS = 25;
  public static final int RPAREN = 31;
  public static final int OR = 3;
  public static final int THEN = 11;
  public static final int SEMI = 24;
  public static final int WHILE = 13;
  public static final int NOT = 4;
  public static final int END = 8;
  public static final int TRUE = 5;
  public static final int IF = 10;
  public static final int LPAREN = 30;
  public static final int GT = 21;
  public static final int LE = 20;
  public static final int NUM = 32;
  public static final int BEGIN = 7;
  public static final int DO = 14;
  public static final int EOF = 0;
  public static final int DIVIDE = 28;
  public static final int MINUS = 26;
  public static final int GE = 22;
  public static final int FALSE = 6;
  public static final int PRINT = 15;
  public static final int error = 1;
  public static final int EQ = 18;
  public static final int ASSIGN = 17;
  public static final int MODE = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "BEGIN",
  "END",
  "EXIT",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "PRINT",
  "READ",
  "ASSIGN",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODE",
  "LPAREN",
  "RPAREN",
  "NUM",
  "IDENT"
  };
}

